### ISSUE TITLE
MASPluginUser.java:122: error: cannot find symbol

### ISSUE THREAD

**Issue by jkbreunig** [CAAPIM/Cordova-MAS-SDK#8]
If I remove this line then the project builds

Error: /Users/(User)/Documents/src/main/ngapp/cordova/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/(User)/Documents/src/main/ngapp/cordova/platforms/android/src/com/ca/mas/cordova/core/MASPluginUser.java:122: error: cannot find symbol
        success(callbackContext, masUser.getAccessToken(), false);
                                        ^
  symbol:   method getAccessToken()
  location: variable masUser of type MASUser

**Comment by manutripathi** [comment]
Hi Jeff, please don't use the develop branch of Cordova plugins (which has the newly introduced access token API). It is still not released, under development. You have to use the `master` branch for your apps.
If you really want to use it then please take the develop of Android-MAS-SDK also, build it and place all the aar files in your apps android/libs, which have the latest code corresponding to the latest cordova plugins.

Can you please explain how you are integrating the cordova plugin in your app and which version of mas libraries you are using.

**Comment by jkbreunig** [comment]
Thanks, I was following the Cordova guide that linked to the develop branch.  http://mas.ca.com/docs/cordova/1.4.00/guides/.  I'm currently following the guide to set up my project.  I'm receiving a permission error when using the master branch

package.json
"dependencies": {
"cordova-plugin-mas-core": "git+https://github.com/CAAPIM/Cordova-MAS-SDK.git"
}
$npm install
npm ERR! cb() never called!

However "cordova-plugin-mas-core": "*" installs without error
package.json
"dependencies": {
"cordova-plugin-mas-core": "*"
}
cordova-plugin-mas-core 0.1.0 "MAS"

**Comment by ysd24** [comment]
Hi Jeff, Can you please give some more details about the permission error.
Also, could you give us the steps you are following to integrate the MAS Plugin.

**Comment by manutripathi** [comment]
It seems that you are downloading the repo Cordova-MAS-SDK instead of Cordova-MAS-Foundation.

Please follow these steps for a starter:
Download the zip : https://github.com/CAAPIM/Cordova-MAS-Foundation/archive/1.4.00.zip 
Next follow the steps mentioned under : http://mas.ca.com/docs/cordova/1.4.00/guides/#set-up-project-and-start-the-sdk

Can you mention, which version of Gateway/OTK and MAG you are using. This impacts the version of Cordova plugin and Android native SDK to be used.
Please let us know if you are able to integrate using these steps or not.

**Comment by jkbreunig** [comment]
this was npm permissions issue
